[package]
name = "write_local"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = { version = "0.11" }
fs-err = { version = "2.9" }
tracing = "0.1"
